import 'package:baymax/core/text_style.dart';
import 'package:flutter/material.dart';

class HelpPage extends StatelessWidget {
  const HelpPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Hero(
            tag: "logo",
            child: Image.asset(
              "assets/logo.png",
              width: 130,
              height: 130,
            ),
          ),
          const SizedBox(
            height: 20,
          ),
          Expanded(
            child: Padding(
              padding: const EdgeInsets.all(20.0),
              child: Container(
                width: double.infinity,
                padding:
                    const EdgeInsets.symmetric(vertical: 10, horizontal: 20),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(20),
                  boxShadow: const [
                    BoxShadow(
                      color: Colors.black38,
                      blurRadius: 20,
                      offset: Offset(0, 10),
                    )
                  ],
                ),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.spaceAround,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "I am Baymax, your personal healthcare companion...\nlet's try to help you.",
                      textAlign: TextAlign.center,
                      style: mainTextStyle.copyWith(
                          fontWeight: FontWeight.w700,
                          color: Colors.black,
                          fontSize: 18),
                    ),
                    Column(
                  crossAxisAlignment: CrossAxisAlignment.start,

                      children: [
                        Text(
                          "Symptom",
                          // textAlign: TextAlign.center,
                          style: mainTextStyle.copyWith(
                              fontWeight: FontWeight.w700,
                              color: Colors.black,
                              fontSize: 18),
                        ),
                        Text(
                          "Symptom is any feeling of illness or physical or mental change that is caused by disease or condition.",
                          // textAlign: TextAlign.center,
                          style: mainTextStyle.copyWith(
                              fontWeight: FontWeight.w500,
                              color: Colors.black,
                              fontSize: 16),
                        ),
                      ],
                    ),
                     Column(
                  crossAxisAlignment: CrossAxisAlignment.start,

                      children: [
                        Text(
                          "ECG Signal",
                          // textAlign: TextAlign.center,
                          style: mainTextStyle.copyWith(
                              fontWeight: FontWeight.w700,
                              color: Colors.black,
                              fontSize: 18),
                        ),
                        Text(
                          "ECG signal is a recording of the heart's electrical activity through repeated cardiac cycles. It is generated by the heartbeats and consists of several waveforms.",
                          // textAlign: TextAlign.center,
                          style: mainTextStyle.copyWith(
                              fontWeight: FontWeight.w500,
                              color: Colors.black,
                              fontSize: 16),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}
